export enum GuestCodeEnum {
  Adela = 'Ad',
  AdelaCouple = '(Ad)',
  Alondra = 'Al',
  AlondraCouple = '(Al)',
  Anabel = 'An',
  AnabelCouple = '(An)',
  Barbara = 'Ba',
  BarbaraCouple = '(Ba)',
  Bertha = 'Be',
  BerthaCouple = '(Be)',
  Enrique = 'En',
  EnriqueCouple = '(En)',
  Esteban = 'Es',
  EstebaCouple = '(Es)',
  Condesa = 'C',
  CondeMayor = 'CMa',
  CondeMenor = 'Cme',
  Duquesa = 'D'
}

export enum GuestEnum {
  Adela = 'Adela',
  AdelaCouple = '(Adela)',
  Alondra = 'Alondra',
  AlondraCouple = '(Alondra)',
  Anabel = 'Anabel',
  AnabelCouple = '(Anabel)',
  Barbara = 'Bárbara',
  BarbaraCouple = '(Bárbara)',
  Bertha = 'Bertha',
  BerthaCouple = '(Bertha)',
  Enrique = 'Enrique',
  EnriqueCouple = '(Enrique)',
  Esteban = 'Estebán',
  EstebaCouple = '(Estebán)',
  Condesa = 'Condesa',
  CondeMayor = 'Conde Mayor',
  CondeMenor = 'Conde Menor',
  Duquesa = 'Duquesa'
}
