name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Angular installation
        run: npm install --global @angular/cli@18.2

      - name: Dependencies installation
        run: npm install

      - name: Build
        run: ng build

      - name: Web Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USER}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: ./dist/browser/
          server-dir: public_html/math/
          dangerous-clean-slate: true
